### 获取 access_token
POST http://192.168.58.101:12888/userCenter/login
Content-Type: application/json

{
  "loginName": "shoumiao",
  "password": "12345678"
}

> {%
  client.global.set("access_token", response.body.data.access_token);
%}


### 查询

GET http://192.168.58.101:12888/admin/tinyUrl/7
Authorization: {{access_token}}

### 增加
POST http://192.168.58.101:12888/admin/tinyUrl/add
Authorization: {{access_token}}

{
  "tiny_url": "testNoLimitAccessTime",
  "original_url": "https://www.google.com"
}

### 访问短链
// 转到 google
GET http://192.168.58.101:12888/tu/hello

### 访问短链  未知短链
GET http://192.168.58.101:12888/tu/qqqqqqqqq

### 访问短链  超时未知短链
GET http://192.168.58.101:12888/tu/limitTest

